# Generated by Django 3.2.7 on 2021-09-20 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_link',
        ),
    ]
