# Generated by Django 3.2.7 on 2021-09-20 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0002_remove_image_image_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_link',
            field=models.ManyToManyField(blank=True, default=False, related_name='likes', to='gram.Profile'),
        ),
    ]
