# Generated by Django 3.2.7 on 2021-09-23 13:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gram', '0003_image_image_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fw',
            field=models.ManyToManyField(related_name='follower', to=settings.AUTH_USER_MODEL),
        ),
    ]
