# Generated by Django 3.2.7 on 2021-09-24 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0006_auto_20210923_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
